orbs: # declare what orbs we are going to use
  node: circleci/node@14.15.0 # the node orb provides common node-related configuration

version: 2.1 # using 2.1 provides access to orbs and other features

workflows:
  app-tests:
    jobs:
      build:
        steps:
          - checkout
          - run:
              name: Install dependencies
              command: npm ci
          - run:
              name: Run Tests
              command: npm run test
